import React from 'react'
import Link from 'gatsby-link'

const SecondPage = () => (
  <section>
    <div className="section" style={{padding: '60px 0px'}}>
      <div className="container">
        <div className="row">
          <div className="col">
            <h1>Why Sterling?</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla aliquid aspernatur culpa quia ducimus, ea accusantium laborum in autem eaque quos enim commodi molestiae error sint fuga rerum, sequi impedit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eum animi consectetur autem optio laborum ab, sunt porro sequi expedita sit nihil harum nulla quidem in, unde veniam aliquam, consequatur reiciendis. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo, ducimus, numquam. Ipsa aspernatur facere sint! Unde pariatur recusandae neque laudantium iste, quam numquam, minus, tempore rem nisi aut laborum quas!Lorem ipsum dolor sit amet, consectetur adipisicing elit. At tempora, vero architecto blanditiis iste impedit, esse deserunt cupiditate in modi debitis quasi necessitatibus magni omnis quam ipsum dolor perferendis delectus.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla aliquid aspernatur culpa quia ducimus, ea accusantium laborum in autem eaque quos enim commodi molestiae error sint fuga rerum, sequi impedit.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla aliquid aspernatur culpa quia ducimus, ea accusantium laborum in autem eaque quos enim commodi molestiae error sint fuga rerum, sequi impedit.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla aliquid aspernatur culpa quia ducimus, ea accusantium laborum in autem eaque quos enim commodi molestiae error sint fuga rerum, sequi impedit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eum animi consectetur autem optio laborum ab, sunt porro sequi expedita sit nihil harum nulla quidem in, unde veniam aliquam, consequatur reiciendis. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo, ducimus, numquam. Ipsa aspernatur facere sint! Unde pariatur recusandae neque laudantium iste, quam numquam, minus, tempore rem nisi aut laborum quas!Lorem ipsum dolor sit amet, consectetur adipisicing elit. At tempora, vero architecto blanditiis iste impedit, esse deserunt cupiditate in modi debitis quasi necessitatibus magni omnis quam ipsum dolor perferendis delectus.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla aliquid aspernatur culpa quia ducimus, ea accusantium laborum in autem eaque quos enim commodi molestiae error sint fuga rerum, sequi impedit.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla aliquid aspernatur culpa quia ducimus, ea accusantium laborum in autem eaque quos enim commodi molestiae error sint fuga rerum, sequi impedit.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla aliquid aspernatur culpa quia ducimus, ea accusantium laborum in autem eaque quos enim commodi molestiae error sint fuga rerum, sequi impedit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eum animi consectetur autem optio laborum ab, sunt porro sequi expedita sit nihil harum nulla quidem in, unde veniam aliquam, consequatur reiciendis. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo, ducimus, numquam. Ipsa aspernatur facere sint! Unde pariatur recusandae neque laudantium iste, quam numquam, minus, tempore rem nisi aut laborum quas!Lorem ipsum dolor sit amet, consectetur adipisicing elit. At tempora, vero architecto blanditiis iste impedit, esse deserunt cupiditate in modi debitis quasi necessitatibus magni omnis quam ipsum dolor perferendis delectus.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla aliquid aspernatur culpa quia ducimus, ea accusantium laborum in autem eaque quos enim commodi molestiae error sint fuga rerum, sequi impedit.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla aliquid aspernatur culpa quia ducimus, ea accusantium laborum in autem eaque quos enim commodi molestiae error sint fuga rerum, sequi impedit.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla aliquid aspernatur culpa quia ducimus, ea accusantium laborum in autem eaque quos enim commodi molestiae error sint fuga rerum, sequi impedit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eum animi consectetur autem optio laborum ab, sunt porro sequi expedita sit nihil harum nulla quidem in, unde veniam aliquam, consequatur reiciendis. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo, ducimus, numquam. Ipsa aspernatur facere sint! Unde pariatur recusandae neque laudantium iste, quam numquam, minus, tempore rem nisi aut laborum quas!Lorem ipsum dolor sit amet, consectetur adipisicing elit. At tempora, vero architecto blanditiis iste impedit, esse deserunt cupiditate in modi debitis quasi necessitatibus magni omnis quam ipsum dolor perferendis delectus.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla aliquid aspernatur culpa quia ducimus, ea accusantium laborum in autem eaque quos enim commodi molestiae error sint fuga rerum, sequi impedit.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla aliquid aspernatur culpa quia ducimus, ea accusantium laborum in autem eaque quos enim commodi molestiae error sint fuga rerum, sequi impedit.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla aliquid aspernatur culpa quia ducimus, ea accusantium laborum in autem eaque quos enim commodi molestiae error sint fuga rerum, sequi impedit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eum animi consectetur autem optio laborum ab, sunt porro sequi expedita sit nihil harum nulla quidem in, unde veniam aliquam, consequatur reiciendis. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo, ducimus, numquam. Ipsa aspernatur facere sint! Unde pariatur recusandae neque laudantium iste, quam numquam, minus, tempore rem nisi aut laborum quas!Lorem ipsum dolor sit amet, consectetur adipisicing elit. At tempora, vero architecto blanditiis iste impedit, esse deserunt cupiditate in modi debitis quasi necessitatibus magni omnis quam ipsum dolor perferendis delectus.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla aliquid aspernatur culpa quia ducimus, ea accusantium laborum in autem eaque quos enim commodi molestiae error sint fuga rerum, sequi impedit.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla aliquid aspernatur culpa quia ducimus, ea accusantium laborum in autem eaque quos enim commodi molestiae error sint fuga rerum, sequi impedit.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla aliquid aspernatur culpa quia ducimus, ea accusantium laborum in autem eaque quos enim commodi molestiae error sint fuga rerum, sequi impedit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eum animi consectetur autem optio laborum ab, sunt porro sequi expedita sit nihil harum nulla quidem in, unde veniam aliquam, consequatur reiciendis. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo, ducimus, numquam. Ipsa aspernatur facere sint! Unde pariatur recusandae neque laudantium iste, quam numquam, minus, tempore rem nisi aut laborum quas!Lorem ipsum dolor sit amet, consectetur adipisicing elit. At tempora, vero architecto blanditiis iste impedit, esse deserunt cupiditate in modi debitis quasi necessitatibus magni omnis quam ipsum dolor perferendis delectus.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla aliquid aspernatur culpa quia ducimus, ea accusantium laborum in autem eaque quos enim commodi molestiae error sint fuga rerum, sequi impedit.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla aliquid aspernatur culpa quia ducimus, ea accusantium laborum in autem eaque quos enim commodi molestiae error sint fuga rerum, sequi impedit.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla aliquid aspernatur culpa quia ducimus, ea accusantium laborum in autem eaque quos enim commodi molestiae error sint fuga rerum, sequi impedit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eum animi consectetur autem optio laborum ab, sunt porro sequi expedita sit nihil harum nulla quidem in, unde veniam aliquam, consequatur reiciendis. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo, ducimus, numquam. Ipsa aspernatur facere sint! Unde pariatur recusandae neque laudantium iste, quam numquam, minus, tempore rem nisi aut laborum quas!Lorem ipsum dolor sit amet, consectetur adipisicing elit. At tempora, vero architecto blanditiis iste impedit, esse deserunt cupiditate in modi debitis quasi necessitatibus magni omnis quam ipsum dolor perferendis delectus.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla aliquid aspernatur culpa quia ducimus, ea accusantium laborum in autem eaque quos enim commodi molestiae error sint fuga rerum, sequi impedit.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla aliquid aspernatur culpa quia ducimus, ea accusantium laborum in autem eaque quos enim commodi molestiae error sint fuga rerum, sequi impedit.</p>
          </div>
        </div>
      </div>
    </div>
  </section>
)

export default SecondPage
